config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">

  <div class="row mt-2">
    <div class="col-md-6"><h3 >Simple Airbnb</h3>
    </div>
    <div class="col-md-6 text-right"><%= link_to "Add a flat", new_flat_path, class: 'btn btn-outline-primary link-unstyled' %>
    </div>
  </div>

  <div class="text-center">
    <h1>All our Flats</h1>
    <p><%= "All #{@flats.count} flats" %></p>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-xs-6 col-md-4 p-0">
      <div class="card p-2 m-2 bg-light">
        <div class="card-title">
          <h3><%= flat.name %></h3>
        </div>
        <div class="card-body">
<i class="fab fa-euro-sign">
          <p><%= flat.address %></p>
          <div class="container ">
           <div >
            <p><i class="fa fa-users"></i><%= flat.number_of_guests %></p>
            <p></i><%= flat.price_per_night %> </p>
          </div>
        </div>
      </div>
      <p><%= link_to "More info", flat_path(flat)  %></p>
    </div>
  </div>
  <% end %>
</div>
</div><i class="fab fa-euro-sign"></i>
<i class="fas fa-euro-sign"></i>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<h3><%= @flat.address %></h3>

<h2>A bit more about this flat...</h2>
<p><%= @flat.description %></p>

<h2>Details</h2>
<p>Price: <%= @flat.price_per_night %></p>
<p>Guests: <%= @flat.number_of_guests %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>